### PR TITLE
Prevents mono header imports when targeting iOS/MacOS.

### PR DESCRIPTION
**Pull request by zgramana**
Resolves mono/Embeddinator-4000#478

### CODE REVIEW

**Comment by tritao** [comment]
approve

**Comment by lemonmojo** [comment]
I can confirm that this PR fixes https://github.com/mono/Embeddinator-4000/issues/478.

**Comment by tritao** [comment]
Thanks for the fix, I'm waiting for CI and will merge it.

**Comment by zgramana** [comment]
Happy to help, and keep up the great work! 🥇

**Pull request merged**
