### PR TITLE
Make TextTransform.exe invocation platform safe. Needs windows implem…

### PR DESCRIPTION
**Pull request by chamons**
…entation

- https://github.com/mono/Embeddinator-4000/issues/337

### CODE REVIEW

**Comment by tritao** [comment]
Thanks for looking into this.

Only issue I can see is that this still forces users to install Xamarin Studio to build the project though. It's an issue for Windows and for macOS Travis CI build. Only alternative I've found was to use https://www.nuget.org/packages/Mono.TextTransform/ to generate `.tt` file.

Another alternative would be to just commit the generated `subscript.cs` file, it should not change very often.

**Comment by chamons** [comment]
I missed that part. Let me look into the nuget. Should be trivial to swap.

**Comment by chamons** [comment]
Ok, that at least uses the nuget instead of XS.

It still doesn't address Windows, and I don't even have a windows dev machine to test it.

@tritao - Could you look into what path bits I'd need to run nuget / the nuget on Windows and I can add that.

If this becomes too much of a mess we can check in output, but I hate to for fear of staleness.

**Comment by tritao** [comment]
Looks good. @realvictorprm is working on a PR with Windows fixes, he should be able to help out there.

**Comment by tritao** [comment]
Anyway regarding the Windows bits, I think it should be a matter of adding the same call to the generator from the nuget, except we do not call via `mono`, but call the `.exe` directly.

**Comment by realvictorprm** [comment]
Excellent, this is exactly what I  planned to fixed also because I alteady ran into the bug thats it's not dowmloaded for window's (workaround was nuget install :wink:).

Anyway, merging the fix is requirement for my PR.

**Comment by realvictorprm** [comment]
@chamons Should I merge the fix into my PR? Without it people cannot try it out instantly because of the missing dep.

**Pull request merged**
