### PR TITLE
Implement support for Linux

### PR DESCRIPTION
**Pull request by tritao**
Lots of changes to CI, build system, support runtime and binder compilation pipeline to support Linux.

### CODE REVIEW

**Comment by realvictorprm** [comment]
I'm curious how fast the Linux CI is compared to the Mac :smile:

**Comment by tritao** [comment]
The builds seem to start within a minute of a push, instead of taking sometimes 30min+...

**Comment by realvictorprm** [comment]
@tritao which C++ are we speaking of? Did you go on with implementing C++ generation?

**Comment by tritao** [comment]
The tests runner uses C++.

**Pull request merged**
